### ISSUE TITLE
Making a design system for Pluto UI and implement them 

### ISSUE THREAD

**Issue by shivam-jainn** [purnima143/Pluto-UI#11]
I want to work on design system for this project .

We will be covering all the major thing required for E-Commerce UI libraries . 

Goal of the UI lib : An E-Commerce website can be made just by our components alone . No additional coding should be required . 

Needs : 1) Documented & Well designed components
2) Components independent of each other 
3) Consistent design

**Comment by purnima143** [comment]
Hi @shivam-jainn , Sure! To begin designing the system, we can follow these steps:

- **Design in Figma:** Start by creating the system design in Figma. Figma is a collaborative design tool that allows multiple people to work on a design project simultaneously.

- **Create a Pull Request (PR):** Once you have designed a component, it's time to create a PR. This PR should include two things:

    - Image of the component: Take a screenshot or export the component as an image (PNG, SVG, or any suitable format).
    - Figma link: Include the Figma link to the design. This will help others access the design file directly.

 -   **Organize the design files:** If you have completed designing the buttons, it's a good practice to organize your design files. Create a folder named 'design-system' inside another folder called 'Button'. This will help maintain a structured design system.

-    **Add the image:** Place the image of the button component inside the 'Button' folder you created. You can use either PNG, SVG, or any other suitable format for the image.

Let me know if you have any further questions or need assistance with anything else!

**Comment by shivam-jainn** [comment]
![Light mode colors](https://github.com/purnima143/Pluto-UI/assets/90458496/ba9af9d2-953c-404f-862e-1990bd15eb3a)

Light Mode Colors

![Dark mode colors](https://github.com/purnima143/Pluto-UI/assets/90458496/43be9c2c-44af-4bfd-81ab-8a76d81dc5b2)

Dark Mode Colors


I came up with a dark mode friendly color palette , is this ok?

**Comment by shivam-jainn** [comment]
![Type Scale](https://github.com/purnima143/Pluto-UI/assets/90458496/41c93b84-f25b-4844-a154-824d7b32a4e9)


Type Scale for the project

**Comment by shivam-jainn** [comment]
![Failed Pop Up](https://github.com/purnima143/Pluto-UI/assets/90458496/0285e0f0-dda5-4050-a311-6cbe79964236)

Failed Pop Up alerts
> A modifiable pop up components that pops up when an error occurs . 
> Has 2 parts : 1) Icon (x)  2) String 
  ** Both of them can be modified according to developer's need**
 
![ATC-dark-fail-component](https://github.com/purnima143/Pluto-UI/assets/90458496/2406d677-321d-4bdd-b37a-f0a98afd3922)
![Payment-fail-dark-component](https://github.com/purnima143/Pluto-UI/assets/90458496/c39ec4fa-ecf1-4dc3-9e6b-09030237aa52)

**Comment by shivam-jainn** [comment]
# BUTTON & IT'S VARIATIONS  (Dark mode)

* 3 types of buttons are available : 1) Outlined 2) Filled 3) Filled with icon 
* Everything is modifiable 

![dark-mode-Outline-button](https://github.com/purnima143/Pluto-UI/assets/90458496/dff74a4f-5678-48f7-b423-b28a895ea9a7)
![dark-mode-button](https://github.com/purnima143/Pluto-UI/assets/90458496/ac0b46b9-fd5e-4c44-9dbf-c5905618232f)
![dark-mode-Icon-button](https://github.com/purnima143/Pluto-UI/assets/90458496/cfe0d1ca-aebe-43f5-a3a8-57b3ca8577d7)

**Comment by Rishika-S-V** [comment]
## I would like to join the design system
 - I would like to add the Tiint and shades for the Colors (Hue), something similar to this
![image](https://github.com/purnima143/Pluto-UI/assets/90262708/7930f2f9-f156-42b5-bc01-724d720fe09b)
 - Further organization of the typography can be split into subcategories such as Display, Headings and Paragraph. and typefaces can be included.
 - Toast notifications can be made subtle and rounded
![image](https://github.com/purnima143/Pluto-UI/assets/90262708/039ae000-3dc5-449c-95ba-900bbf32d452)
 - Buttons can have more variations like Primary, secondary and ghost buttons and icons with different border-radius and fully rounded edges can be appreciated.
![image](https://github.com/purnima143/Pluto-UI/assets/90262708/1a0ae9fb-c852-446f-abb7-4152d5aa6487)

_* all the examples provided are from my collection and will be customised specifically for this project._

**Comment by Lovelyfin00** [comment]
Hey @kisshan13 @shivam-jainn 
Please join the project channel on discord by going to #self-role and selecting Pluto UI if you haven't done so.

**Comment by shivam-jainn** [comment]
@Lovelyfin00 @AdityaSingh-02 @purnima143  https://www.figma.com/file/a9ny3G0uoC73qH3vPwZ1vj/Untitled?type=design&node-id=0%3A1&t=IN9CYUnSDqce3YKZ-1

This is the figma file i am using for designing these components . Any suggestions would always be welcome :)

**Comment by Lovelyfin00** [comment]
Hey @shivam-jainn 
I would like you and @Rishika-S-V  to work together on designs

**Comment by shivam-jainn** [comment]
> I also want to contribute into designing part may I?

Hey ! Connect with me on discord and we can definitely work together (if you want to)
pablowww#7316

I am extremely sorry for the late reply ! I have my sem ends going on :)

**Comment by shivam-jainn** [comment]
> Hey @shivam-jainn I would like you and @Rishika-S-V to work together on designs So that means working on the same figma file but designing different components

Yea sure thing !
@Rishika-S-V pablowww#7316 Hit up ! Let's work on this

**Comment by Lovelyfin00** [comment]
> > I also want to contribute into designing part may I?
> 
> Hey ! Connect with me on discord and we can definitely work together (if you want to) pablowww#7316
> 
> I am extremely sorry for the late reply ! I have my sem ends going on :)

It's ok. I'll send you a dm on discord.
