### ISSUE TITLE
Create Navigation Component

### ISSUE THREAD

**Issue by nishitapande** [purnima143/Pluto-UI#15]

**Comment by nishitapande** [comment]
@purnima143 please assign this issue to me. thanks

**Comment by nishitapande** [comment]
ok. thanks.

**Comment by khushi767** [comment]
Please assign me this issue under GSSOC'23

**Comment by nishitapande** [comment]
@khushi767 I am working on this issue. please read the readme file, and choose the component of your choice and work on that

**Comment by Lovelyfin00** [comment]
I'll close this issue now since it's being worked on by someone else
