### ISSUE TITLE
Product Card 

### ISSUE THREAD

**Issue by shivam-jainn** [purnima143/Pluto-UI#21]
# PRODUCT CARD

* Product card has 2 parts : 1) Product's image 2) Product's description

### Product's description

* Product's description contains mainly of : 1) Product title 2) Product Description paragraph 3) Add to Card button of accent color (CTA) 4)Price

## DARK MODE
![Product-card-dark](https://github.com/purnima143/Pluto-UI/assets/90458496/00e40e14-97db-4c38-b931-480bd06448c5)

## LIGHT MODE
![Product-card-light ](https://github.com/purnima143/Pluto-UI/assets/90458496/22dba6fc-2818-4aa7-8c9b-56cd6dafc9da)

### Things that can be added on to Product cards

[ ] Badges

**Comment by Manvi1902** [comment]
I would like to contribute this.
I am able to responsive & designer product card.

my sample card design is 
![image](https://github.com/purnima143/Pluto-UI/assets/109518835/d016d6ae-1d22-4c92-b3a0-e2e2563fcffb)

**Comment by shivam-jainn** [comment]
> I would like to contribute this. I am able to responsive & designer product card.
> 
> my sample card design is ![image](https://user-images.githubusercontent.com/109518835/240171390-d016d6ae-1d22-4c92-b3a0-e2e2563fcffb.png)

Hey @Manvi1902 !!!
 I have pushed change and created card . Maybe you can create a badge component separately and then make a variant of the card with badge included in it ? 
 We can discuss on this idea :)

**Comment by Manvi1902** [comment]
sure
