### ISSUE TITLE
Design: Create designs for the Navigation component

### ISSUE THREAD

**Issue by Lovelyfin00** [purnima143/Pluto-UI#32]
## Issue summary

There is currently no design for the navigation component and in order for the project to have a uniform styleguide, a design has to be created for each of the components.

## Proposed fix

Create a design for the navigation component using the colors of the project which is already given in the README. 

## Tasks

 - [ ] Navigation bar
 - [ ] Mega menu
 - [ ] Breadcrumbs
 - [ ] Sidebar

NB: There is no font family chosen yet, so you would have to pick one yourself

After you start working on the issue, i.e designing, drop a link to the figma page here and give me alongside @AdityaSingh-02 and @purnima143 edit access

**Comment by Rishika-S-V** [comment]
Figma Link- https://www.figma.com/file/DndFxZ6d8kbndhCiPwQLlo/Pluto-UI-Navbar-Component?type=design&node-id=0%3A1&t=oeo6rdARkLjULwCo-1

**Comment by Lovelyfin00** [comment]
Awesome
Thanks!
