### ISSUE TITLE
creating a react app with proper nav bar with elements

### ISSUE THREAD

**Issue by LegendSumeet** [purnima143/Pluto-UI#4]
can you assign this to me, I want to work on this under GSSoC'23

**Comment by Uma-Shankar0927** [comment]
I am proficient in React and basically MERN stack technology. I can implement the described task. Please can you assign me the task?

**Comment by LegendSumeet** [comment]
@purnima143

**Comment by purnima143** [comment]
@LegendSumeet Can you work on other components, Navbar one is already assigned
