### ISSUE TITLE
[Design] Implement spinner component

### ISSUE THREAD

**Issue by rahulaarora** [purnima143/Pluto-UI#44]
- [ ] There is no similar existing issue
- [ ] This is a part of GSSOC23

## Description 
Implementing the spinner component according to PlutoUI Design language as it is not implemented yet. It will be implemented in different colours and sizes.

**Comment by rahulaarora** [comment]
@Lovelyfin00 I would like to work on this, please assign it to me

**Comment by Lovelyfin00** [comment]
Hey @rahulaarora 
I just saw that someone else created a PR addressing this issue😥

**Comment by Lovelyfin00** [comment]
I'll close this now since it's a duplicate issue
