### ISSUE TITLE
Frontend: Build Product card Component for both light and dark modes

### ISSUE THREAD

**Issue by Lovelyfin00** [purnima143/Pluto-UI#47]
## Issue Summary
The design for Product card as part of the Product component has been completed and now it needs to be built using our chosen tech stacks. The Product card has to be inside the Product component story

## Figma link

The design for the [Product card can be found here](https://www.figma.com/file/DndFxZ6d8kbndhCiPwQLlo/Pluto-UI-Components?type=design&node-id=148-349&t=x9Zr8FppIi1g9REk-0). Please make sure what you build follows the design.

## Suggested fix
 - Build the Product card component following the design in the Figma file. 
 - Make sure your codes are maintainable and legible.
 - After coding the component using React and scss, create storybook for the component.
 - Test it out on your end and make sure it's working properly.

## Coding Rules
- Let your codes look neat and readable
- No unnecessary spacing and always leave one empty line after each code block
- Separate each word with a hyphen `-` in your scss classes, ids.

## PR Rules
- Link the issue your PR is for by saying `Fixes #PRNumber` 
- Add a description of what your PR is about
- Add screenshots or video of the working implementation of your PR

<hr/>

### Light mode

<br/>

<img src="https://github.com/purnima143/Pluto-UI/assets/38161296/0e0efc70-d84f-4d3f-a3e7-d586521c9c88" style="height: 4rem; width: 100%" />

<hr/>

### Dark mode

<br/>

<img src="https://github.com/purnima143/Pluto-UI/assets/38161296/6b83136d-a076-4dc5-a318-4f1bf12fa244" style="height: 4rem; width: 100%" />

**Comment by shivam-jainn** [comment]
I am working on this !

**Comment by bhoomikhurana** [comment]
Has this work been done yet?I would like to take up this issue and apply my skills into it

**Comment by Lovelyfin00** [comment]
Yes. Someone is working on it
