### ISSUE TITLE
Frontend: Build the Product List/grid view Component for both light and dark mode

### ISSUE THREAD

**Issue by Lovelyfin00** [purnima143/Pluto-UI#71]
## Issue Summary
The design for Product Product List/grid view as part of the Product component has been completed and now it needs to be built using our chosen tech stacks. The Product List/grid view has to be inside the Product component story

## Figma link

The design for the [Product List/grid view can be found here](https://www.figma.com/file/DndFxZ6d8kbndhCiPwQLlo/Pluto-UI-Components?type=design&node-id=148-349&t=x9Zr8FppIi1g9REk-0). Please make sure what you build follows the design.

## Suggested fix
 - Build the Product List / grid view component following the design in the Figma file. 
 - Make sure your codes are maintainable and legible.
 - After coding the component using React and scss, create storybook for the component.
 - Test it out on your end and make sure it's working properly.

## Coding Rules
- Let your codes look neat and readable
- No unnecessary spacing and always leave one empty line after each code block
- Separate each word with a hyphen `-` in your scss classes, ids.

## PR Rules
- Link the issue your PR is for by saying `Fixes #PRNumber` 
- Add a description of what your PR is about
- Add screenshots or video of the working implementation of your PR

<hr/>

### Light mode

<br/>

<img src="https://github.com/purnima143/Pluto-UI/assets/38161296/e40d6dbd-2f7a-4848-ba15-09f0f52953f2" style="height: 4rem; width: 100%" />

<hr/>

### Dark mode

<br/>

<img src="https://github.com/purnima143/Pluto-UI/assets/38161296/ada248a2-e883-49af-b721-54d3076de400" style="height: 4rem; width: 100%" />

**Comment by naveeng2402** [comment]
pl assign me to the issue

**Comment by Lovelyfin00** [comment]
Hey @naveeng2402 
I'd like you to focus on one issue before showing interest in another

**Comment by naveeng2402** [comment]
Done👍

**Comment by Lovelyfin00** [comment]
Done with what exactly? @naveeng2402

**Comment by shivam-jainn** [comment]
Has this issue been assigned to someone else?

**Comment by Lovelyfin00** [comment]
No @shivam-jainn 
You can work on it before I review your other PR

**Comment by tripathishipra** [comment]
Hi , I am contributor under GSSOC'23 and I am eager to showcase my skills and make a meaningful contribution to this project.
Kindly assign me this issue. @Lovelyfin00

**Comment by shivam-jainn** [comment]
I am working on it !

**Comment by tripathishipra** [comment]
okay

**Comment by PatilHarshh** [comment]
@Lovelyfin00 this issue is still open, if yes , I am interested to contribute!

**Comment by Lovelyfin00** [comment]
Hey @PatilHarshh 
It’s not available 
There’s already a PR for it
You can checkout other frontend issues and new ones would be created tomorrow
