### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by harshit-tiwaari** [purnima143/Pluto-UI#73]
A minimalistic and interactive home page is necessary to make interest of users and ecommerce website makers. I Want to make design like below!
![image](https://github.com/purnima143/Pluto-UI/assets/104323483/7cd2b02f-f794-407b-a816-3f39dc7c0671)

**Comment by pratibha-iit** [comment]
you want to exact same.

**Comment by harshit-tiwaari** [comment]
not same but something like it

**Comment by pratibha-iit** [comment]
Can I change something 
assign this work to me

**Comment by purnima143** [comment]
Right now we are focusing on component elements. We will focus on main website later as this repo is totally dedicated to the library. You can check other issues or create new one @harshit-tiwaari  @pratibha-iit
