### ISSUE TITLE
Make a seperate CONTRIBUTING.md file

### ISSUE THREAD

**Issue by sumitkr2000** [purnima143/Pluto-UI#75]
Hey @purnima143 I want to make a separate contributing.md files so that it will be easy for the contributors to know the flow of the project. Please assign me this issue. Thank you!

**Comment by Snigdha2712** [comment]
Kindly assign this issue to me under gssoc23 @purnima143

**Comment by sumitkr2000** [comment]
@purnima143 Please assign me this issue so that I can start working on it.

**Comment by Lovelyfin00** [comment]
Hi @sumitkr2000 
I'm not sure we need that right now
cc: @AdityaSingh-02

**Comment by sumitkr2000** [comment]
Okay np @Lovelyfin00
