### ISSUE TITLE
ADD ABOUT US COMPONENT

### ISSUE THREAD

**Issue by pradhuman09** [purnima143/Pluto-UI#8]
I want to make about us component for the Pluto-UI.
**Please assign me this task**

**Comment by nishitapande** [comment]
Please assign me this task. Thank you

**Comment by purnima143** [comment]
Hi @pradhuman09 @nishitapande , can you take other components to work on. This issue is not required now.

**Comment by nishitapande** [comment]
@purnima143 sure. please assign me someother issue, related to front-end . Thank you

**Comment by purnima143** [comment]
Hi @nishitapande    
- Create an issue specifically for the **breadcrumb** component and assign it to me.
-  Alternatively, refer to the **readme** file for the list of available components. Choose the component you would like to work on, create an issue for it, and assign it accordingly.

Please let me know which option you prefer, or if there's anything else I can assist you with!

**Comment by pradhuman09** [comment]
@purnima143 sure. please assign me some other issue, related to front-end . Thank you
