### ISSUE TITLE
Adding dependabot.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [purnima143/Pluto-UI#80]
*We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.*

@purnima143 please assign me this issue under gssoc'23.

**Comment by purnima143** [comment]
Sure @Anshika-Jain02

**Comment by AdityaSingh-02** [comment]
hey, @purnima143 we have a PR regarding this issue before merging it we need to add a level to this issue. I was wondering what level  should we use level 2 or level 3
